// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yorhxiqmrtamxrvjqlwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvcmh4aXFtcnRhbXhydmpxbHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODA2NjksImV4cCI6MjA2Njg1NjY2OX0.FX0tHv3XBGrDDoab9wPdwIEEOiddRUAa9zM62gZ9Edo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});